"""empty message

Revision ID: 02a4364ff5a3
Revises: 4ad441d2c2da
Create Date: 2020-05-09 15:31:49.280780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02a4364ff5a3'
down_revision = '4ad441d2c2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('basket', 'basket_price')
    op.add_column('basket_item', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('basket_item', 'item_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_item', sa.Column('item_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('basket_item', 'price')
    op.add_column('basket', sa.Column('basket_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('basket', 'price')
    # ### end Alembic commands ###
