"""empty message

Revision ID: 02b958d4365a
Revises: 288c2ca0cfa3
Create Date: 2020-05-07 15:01:57.093755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b958d4365a'
down_revision = '288c2ca0cfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orders', ['id'])
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('position', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'orders', type_='unique')
    # ### end Alembic commands ###
