"""empty message

Revision ID: 1612e5ad76d6
Revises: 7ffa63359047
Create Date: 2020-05-08 15:21:11.774390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1612e5ad76d6'
down_revision = '7ffa63359047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_basket')
    op.create_unique_constraint(None, 'order_items', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='unique')
    op.create_table('order_basket',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], name='order_basket_basket_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_basket_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'basket_id', name='order_basket_pkey')
    )
    # ### end Alembic commands ###
