"""empty message

Revision ID: 1a049d528fe3
Revises: 5e8b9551f135
Create Date: 2020-07-13 14:17:41.718812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a049d528fe3'
down_revision = '5e8b9551f135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_item_basket_id_fkey', 'basket_item', type_='foreignkey')
    op.create_foreign_key(None, 'basket_item', 'basket', ['basket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket_item', type_='foreignkey')
    op.create_foreign_key('basket_item_basket_id_fkey', 'basket_item', 'basket', ['basket_id'], ['id'])
    # ### end Alembic commands ###
