"""empty message

Revision ID: 2ba781ed6105
Revises: 1a049d528fe3
Create Date: 2020-07-14 18:20:17.547100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba781ed6105'
down_revision = '1a049d528fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vegetables_vegetable_name_id_fkey', 'vegetables', type_='foreignkey')
    op.create_foreign_key(None, 'vegetables', 'vegetable_name', ['vegetable_name_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vegetables', type_='foreignkey')
    op.create_foreign_key('vegetables_vegetable_name_id_fkey', 'vegetables', 'vegetable_name', ['vegetable_name_id'], ['id'])
    # ### end Alembic commands ###
