"""empty message

Revision ID: 9a272201d0bc
Revises: 33cdb1679752
Create Date: 2020-05-07 17:12:47.117529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a272201d0bc'
down_revision = '33cdb1679752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('administrators_id_fkey', 'administrators', type_='foreignkey')
    op.create_foreign_key(None, 'administrators', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('consumers_id_fkey', 'consumers', type_='foreignkey')
    op.create_foreign_key(None, 'consumers', 'users', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consumers', type_='foreignkey')
    op.create_foreign_key('consumers_id_fkey', 'consumers', 'users', ['id'], ['id'])
    op.drop_constraint(None, 'administrators', type_='foreignkey')
    op.create_foreign_key('administrators_id_fkey', 'administrators', 'users', ['id'], ['id'])
    # ### end Alembic commands ###
