"""empty message

Revision ID: fa9e2a74d9af
Revises: 9a272201d0bc
Create Date: 2020-05-07 18:07:29.430965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9e2a74d9af'
down_revision = '9a272201d0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordered_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ordered_date')
    # ### end Alembic commands ###
